development:
  adapter: postgresql
  encoding: unicode
  database: parakeet_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: parakeet_test
  pool: 5
  host: localhost